version: 2
jobs:
  build:
    docker:
      - image: node:12

    working_directory: ~/buddy/test-react-app-bdy

    steps:
      - add_ssh_keys:
          fingerprints:
            - "6d:b6:73:17:67:24:6a:a4:49:3a:de:ac:36:9a:5c:16"
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      # run tests!
      - run: npm test

      - run: npm build