version: 2
jobs:
  build:
    docker:
      - image: node:12

    working_directory: ~/buddy/test-react-app-bdy

    steps:
      - add_ssh_keys:
          fingerprints:
            - "76:12:99:69:40:15:a3:7d:e4:fd:1c:a9:b1:f6:bd:fa lukasz.czulak@gmail.com"
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      # run tests!
      - run: npm test

      - run: npm build